### ISSUE TITLE
Cannot obtain query string parameters

### ISSUE THREAD

**Issue by guidomb** [spine/spine#273]
When using routing with `history: true` it is not possible to obtain the query string. For example given the route `/foo?param1=1&param2=2&param2=3` when the params variables is passed to the controller it does not have the query string. It would be nice to have something like `params.query` that returns 

``` json
{
param1: 1,
param2: [2, 3]
}
```

**Comment by richard-flosi** [comment]
I know this is old, but this is still an issue.
From what I can tell the page does not refresh, so I don't think that's the issue.
Looking at the source code I think I have a fix.

First, this actually seems to work now when using `Spine.Route.navigate`, but doesn't work on the initial load of the page.

I issue with the initial page load is in the `getPath` method here:
https://github.com/spine/spine/blob/dev/src/route.coffee#L139

```
  @getPath: ->
    if @history
      path = window.location.pathname
      path = '/' + path if path.substr(0,1) isnt '/'
    else
      path = window.location.hash
      path = path.replace(hashStrip, '')
    path
```
Note: it is only getting the `pathname` without the query string. Replacing that line with:
`path = window.location.href.replace(window.location.origin, '');`
will preserve the complete url without the http://hostname.com

Then routes like: `/foo/:bar?q=:baz` will work both on initial load and with `navigate()`.

The remaining issue is that when your query parameter value in `q` which will be available as `params.baz` in this example, will still be url encoded and will need to be decoded with `decodeURIComponent(params.baz)`.
I'm not sure where that can happen yet or if that should happen in Spine. It looks like it could happen in  `Manager.prototype.change` before the args are sent to `activate` in `return current.activate.apply(current, args);`
https://github.com/spine/spine/blob/dev/src/manager.coffee#L29-L33
Although, `deactivate` is called with `args` too which I didn't know before, maybe that should get the updated args as well?

**Comment by aeischeid** [comment]
I don't have time to dive into in this in depth today, but it looks like you are on the trail. Producing a failing test for the problem as it currently exists might be a good step to steer the discussion and the solution. Feel free to open a new issue too if the problem isn't quite the same as it used to be. if it is the same we can re-open.

**Comment by richard-flosi** [comment]
I've got this changed patched in our app and will work on a failing test and pull request asap.
One bug we just found was with IE11. Apparently `window.location.origin` is `undefined` during the initial page load.
