### ISSUE TITLE
Ajax-- when update one newly created model,  "create" event is raised by model as Ajax response arrived.

### ISSUE THREAD

**Issue by shaoyangyu** [spine/spine#341]
Hi.
   I am not sure if the below behavior is correct:
   "create" event is raised as Ajax response arrived, but the request is update (PUT ).

  Scenario: Todos sample + Ajax

  step1 :  create one task 
          can see the POST request data :                     {"name":"sss","ownerid":2,"id":"c-2"}
              and the response from server:                     {"id":"37","ownerid":2,"name":"sss","done":null}
  step2: update the task. the PUT request data:         {"name":"sss","done":1,"ownerid":2,"id":"37"}
              and the response from server :                    {"id":37,"ownerid":2,"name":"sss","done":1}

  then one "create" event is raised.   "addOne" method of the Todos sample is called ~!

**Comment by adambiggs** [comment]
> then one "create" event is raised.

One `create` event is expected in this scenario.
