### ISSUE TITLE
Binding to 'refresh' leads to duplicate triggers

### ISSUE THREAD

**Issue by dkapadia** [spine/spine#503]
Hi all,

I'd like to trigger a callback whenever Collection.fetch() completes fetching data from my server, but when I bind a callback to the 'refresh' event, I find that (since #486) it also gets called when a model is created. 

The test case below hopefully describes the problem accurately - it relies on some setup in ajax.js.

Is 'refresh' not the correct event to be listening for in this use case, or is this a bug?

Thanks!

```javascript
  it("should not trigger a collection refresh event when creating a model", function(){
    spyOn(jQuery, "ajax").andReturn(jqXHR);

    // callback is a method that we'd like to trigger 
    //  when the collection is refreshed, via User.fetch()
    var callback = jasmine.createSpy('SomeCollectionAction');
    User.bind('refresh', callback);

    User.create({first: "Hans", last: "Zimmer"});
    // However, when the response to the create request is resolved
    //  the callback above is triggered, which is not what we want.
    var newAtts = {first: "Hans", last: "Zimmer", id: "IDD"};
    jqXHR.resolve(newAtts);

    expect(callback).not.toHaveBeenCalled();
  });
```

**Comment by aeischeid** [comment]
with spine 1.4+ events have been reworked some and the refresh event gets fire much less often. I don't know that that solves this problem exactly, but thinking I will close this as the real solution will be handled by some sort of overarching promise implementation in spine
