### ISSUE TITLE
jQuery Object Lost when clear the global dom scope

### ISSUE THREAD

**Issue by lujiajing1126** [spine/spine#566]
When you use
```
 $('body').html require('views/some-template')
```
then you change to the controller by using event-trigger instead of re-instantiating the controller(usually recall constructor function)
```
// projectsController.coffee
@navigate '/projects'
// index.coffee
@routes
    "": ->
	@html require('views/index')
    "/login": ->
	@loginController = new Login(el: $('body'))
    "/projects": ->
	@projectController.active()
```
the ```@el``` will not pointer to the dom even if the dom existed

I will fix it later in the ```refreshElements``` of ```Spine.coffee```
by re-finding the DOM using the old id or classes

**Comment by aeischeid** [comment]
so, this only is a problem if replacing the element that the spine app is initially set up to work from or one higher in the DOM tree?

**Comment by aeischeid** [comment]
I was thinking a similar thing. "don't do that"

**Comment by aeischeid** [comment]
Think I will close this. As @adambiggs mentioned if you want to replace controllers nested inside of other controllers you should manage that explicitly. There is just to much to go wrong for Spine to try to handle that for you

**Comment by lujiajing1126** [comment]
@adambiggs Thx U for the help.
I may not understand the philosophy of the Spine architecture very well. And I admit my solution is less efficient but I still feel uncomfortable while handling such problem so that i couldn't substitute the whole body dom free.
I haven't encountered such problem in EmberJS because of another fully different view handle solution. So I wonder if the design of the Spine View Module is not so reasonable.
