### ISSUE TITLE
ajaxSuccess event no longer getting item as first argument 

### ISSUE THREAD

**Issue by aeischeid** [spine/spine#573]
in Spine 1.3.2 the record item was passed as the first argument on ajaxSuccess events like so:

```coffee
class Asset extends Spine.Model
    @extend Spine.Model.Ajax
    
    @bind 'ajaxSuccess', (item, data, status, xhr)->
        console.log item
        Spine.trigger('notify', status) unless status is 'nocontent'
```

In 1.4.0 `item` is not included, so you would need to rewrite the callback.

    @bind 'ajaxSuccess', (data, status, xhr)->

The question is what do people think of this? should instances be passed on when a collection bound event is triggered by an instance?

**Comment by cengebretson** [comment]
What is the value of the `this` object in the 1.4.0 callback?

**Comment by aeischeid** [comment]
I am always a little unclear on what it is called technically, but the Model Collection object or in this case `Asset`

**Comment by aeischeid** [comment]
the binder example above could be written like this if it were outside of the model. 

```coffee
Asset.bind 'ajaxSuccess', (item, data, status, xhr) ->
```

**Comment by cengebretson** [comment]
If you bind an `ajaxSuccess` with the actual record then would `this` be the record that initiated the ajax call? I think as long as its consistent that the class bound events are associated with the class and the record bound events are tied to the record then 1.4.0 approach is good.

**Comment by aeischeid** [comment]
I actually am thinking I want it back the way it was. Class level events that fire on the instance should pass along the instance. This is what happens in the `create`, `update`, and `refresh` events, so it seems like it should happen for `ajaxSuccess` as well. @adambiggs since you recently reworked some of the events stuff do you have any quick insight into how to fix this, or an opinion on if it should be fixed.
