### ISSUE TITLE
testing new issue

### ISSUE THREAD

**Issue by ite101** [spine/spine#576]
hello world :)

**Comment by ite101** [comment]
reply me if you see this

**Comment by kellybbf** [comment]
sorry to ask again, i forgot your name

**Comment by ite101** [comment]
Kay :)

**Comment by ite101** [comment]
why closed?

**Comment by aeischeid** [comment]
why opened?

**Comment by ite101** [comment]
we try to learn how to use this. it's part of school project. 
so, why closed?
