### ISSUE TITLE
Crashes if the browser doesn't support localStorage

### ISSUE THREAD

**Issue by ins429** [spine/spine#583]
Crashes if a model is using localStorage and browser doesn't support localStorage.
~~~
// from Safari private browsing
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
~~~

Should extend `Spine.Model.Local` only If localStorage is supported.

Such line(https://github.com/spine/spine/blob/6a023ab074b4960d3588aa67a5efbb3208321b83/src/local.coffee#L4-L6) should check if the browser supports localStorage:
~~~
 extended: ->
    if window.localStorage
        @change @saveLocal
        @fetch @loadLocal
~~~

**Comment by richard-flosi** [comment]
:+1:
