### ISSUE TITLE
`isBlank` suppose to check the number?

### ISSUE THREAD

**Issue by ins429** [spine/spine#587]
Validating any number with `isBlank` will always fail.
~~~
> Spine.isBlank(1000)
true
> Spine.isBlank(Number(1000))
true
~~~

Not sure if this is intended.

**Comment by aeischeid** [comment]
isBlank is not something I use. an old utility method/shim that has existed from before I ever used or maintained Spine. looks like in in essence  it is just checking if the thing is truthy... sortof... 

``` coffee
  isBlank = (value) ->
  return true unless value
  return false for key of value
  true
```

**Comment by aeischeid** [comment]
examining it a little bit `isBlank` does seem pretty broke, and not useful... it is used in only one place withing spine core or modules. in the ajax module when checking the recordResponse. I would think we could use jqeurys $.isEmptyObject there, but zepto doesn't seem to have a corresponding method...

**Comment by aeischeid** [comment]
I made is blank go away in 1.5.0 :) 

thanks!

**Comment by ins429** [comment]
Thanks.
@richard-flosi, @supernintendo FYI.
