### ISSUE TITLE
Support multiple remote hosts (override Spine.Model.host)

### ISSUE THREAD

**Issue by rdarrelbonner** [spine/spine#594]
I have an application where I'll be looking to interact with multiple servers and will need to ability to specify the host for each of the models.

My current thought is to specify the remote host on the model and have that value override the default Spine.Model.host.

**Comment by aeischeid** [comment]
yep, that should do it. You can also set a `url` prop on the model that includes the full path you intend to use for that model.

I am going to close the issue, just because there isn't really anything to do.
