### ISSUE TITLE
1.6 ajax create success and then auto ajax update

### ISSUE THREAD

**Issue by kkxlkkxllb** [spine/spine#597]
2c6fc40b6ed495730a27953cd44bb7960a2817f5 
This commit caused problem when i do `SomeModel.create data` use ajax, then it send a PUT request after sent a POST request, because the id in POST request's response doesn't equal to the auto created cid. i think ChangeID method should be put in Ajax.disable

**Comment by adambiggs** [comment]
Thanks for the bug report, I've added a failing unit test.

@aeischeid @richard-flosi any thoughts on this?

**Comment by aeischeid** [comment]
I had only glanced at this yesterday. The failing test gives me a much better idea what is going on, so thanks for that. As for how to fix... I will have to dig into it and check back.

**Comment by richard-flosi** [comment]
I never noticed an extra PUT after a create. What version did this start happening in?

**Comment by aeischeid** [comment]
probably introduced in 1.6

**Comment by kkxlkkxllb** [comment]
yes, just happen in 1.6 version

**Comment by aeischeid** [comment]
we have a almost circular call going on. 

because Model.create calls save and save calls create or update... I threw in some log statements and it looked like this:

```
first model create... spine.js:473:7
next model instance save...? spine.js:650:7
then ajax extension create...? ajax.js:279:7
next model instance save...? spine.js:650:7
finally ajax extension update...
```
seems like might be a tricky fix. I am going to play around a bit and see what I can figure out

**Comment by aeischeid** [comment]
removing the `@save()` from the changeId method makes all tests pass. I am still trying to reason out if that is really a good thing to do though.

**Comment by aeischeid** [comment]
I think this can be closed. @kkxlkkxllb can you test with latest spine (1.6.1) and report back.

**Comment by kkxlkkxllb** [comment]
@aeischeid Thx, i have tested it with 1.6.1, it looks good.
