### ISSUE TITLE
spinejs.com domain registration has expired

### ISSUE THREAD

**Issue by rdarrelbonner** [spine/spine#610]
@maccman documentation is currently not available due to the registration lapse in spinejs.com.

Domain Name: SPINEJS.COM
Status: clientHold https://icann.org/epp#clientHold
Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Status: pendingDelete https://icann.org/epp#pendingDelete
Updated Date: 06-dec-2016
Creation Date: 21-sep-2011
Expiration Date: 21-sep-2016

**Comment by aeischeid** [comment]
I've been trying to take steps to get this resolved, but no luck so far. In the meantime we've slowly been working on a port of the rails app here https://github.com/spine/spine.site repo into a new site made with [Wintersmith](http://wintersmith.io/) to be hosted at http://spine.github.io/ - source for that is currently on branches of this repo https://github.com/spine/spine.github.io any help would be very welcome!

**Comment by rdarrelbonner** [comment]
ya, last year when it happened I sent Alex a message on twitter and he was able to get it back up pretty quickly.

**Comment by aeischeid** [comment]
http://spine.github.io/ is up an running pretty well now :)
