### ISSUE TITLE
Documentation link in README.md is broken

### ISSUE THREAD

**Issue by joeljames** [spine/spine#612]
The documentation link mentioned in https://github.com/spine/spine#learn-it is broken. That link takes me to http://spinejs.com/ which says `SpineJs.com is coming soon`. Can some one direct me to the documentation?

**Comment by aeischeid** [comment]
We had issues with spinejs.com. Honestly I don't know who has published what is there now... That is super odd to me. Anyway, I ported documentation to http://spine.github.io/

**Comment by joeljames** [comment]
Thanks @aeischeid
